-- 코드를 입력하세요
--USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계하는 SQL문을 작성해주세요. 결과는 년, 월, 성별을 기준으로 오름차순 정렬해주세요. 이때, 성별 정보가 없는 경우 결과에서 제외해주세요.
-- SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH, GENDER, COUNT(USER_ID) AS USERS
-- FROM (SELECT * FROM ONLINE_SALE S
-- JOIN USER_INFO I USING (USER_ID))
-- WHERE GENDER IS NOT NULL
-- GROUP BY EXTRACT(YEAR FROM SALES_DATE),EXTRACT(MONTH FROM SALES_DATE),GENDER
-- ORDER BY 1,2,3


SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM
    (SELECT * FROM ONLINE_SALE S JOIN USER_INFO I USING (USER_ID))
WHERE
    GENDER IS NOT NULL
GROUP BY
    EXTRACT(YEAR FROM SALES_DATE),
    EXTRACT(MONTH FROM SALES_DATE),
    GENDER
ORDER BY
    1, 2, 3;