-- 코드를 입력하세요

-- SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR
--     ,EXTRACT(MONTH FROM SALES_DATE) AS MONTH
--     ,COUNT(OS.USER_ID) AS PURCHASED_USERS
--     ,ROUND(COUNT(DISTINCT OS.USER_ID)/
--         (SELECT COUNT(*) FROM USER_INFO
--         WHERE EXTRACT(YEAR FROM JOINED) = 2021),
--            1) AS PURCHASED_RATIO
-- FROM ONLINE_SALE OS
--     JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
-- WHERE EXTRACT(YEAR FROM JOINED) = 2021
-- GROUP BY EXTRACT(YEAR FROM SALES_DATE),EXTRACT(MONTH FROM SALES_DATE)
-- ORDER BY YEAR, MONTH




SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR
, TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH
, COUNT(DISTINCT(USER_ID)) AS PUCHASED_USERS
, ROUND(COUNT(DISTINCT(USER_ID)) / (SELECT COUNT(USER_ID)
                                    FROM USER_INFO 
                                    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                  FROM USER_INFO 
                  WHERE TO_CHAR(JOINED, 'YYYY') = '2021')
GROUP BY TO_CHAR(SALES_DATE, 'YYYY') , TO_CHAR(SALES_DATE, 'MM')
ORDER BY YEAR, MONTH;