-- 코드를 입력하세요
SELECT * FROM 
(SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NOT NULL AND O.ANIMAL_ID IS NULL
ORDER BY DATETIME)
WHERE ROWNUM<=3