-- 코드를 입력하세요
-- WRITER_ID = USER_ID
-- 1. 조건 테이블 도출: 
-- BOARD에서 WRITER ID 별 STATUS가 DONE인 레코드들의 PRICE의 총합 >= 700000
-- 2. 조건 테이블 SELECT: WRITERID PRICE합
-- 3. 조건 테이블에 유저 테이블 조인

-- SELECT B.WRITER_ID, U.NICKNAME, B.SUM(PRICE) FROM USED_GOODS_BOARD B
-- JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
-- GROUP BY B.WRITER_ID HAVING B.STATUS LIKE 'DONE'
-- WHERE B.SUM(PRICE)>=700000


-- SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES 
-- FROM USED_GOODS_USER U
-- JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
-- GROUP BY U.USER_ID, U.NICKNAME
-- ON STATUS LIKE 'DONE'
-- WHERE SUM(B.PRICE) >=700000
-- ORDER BY SUM(B.PRICE)


SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.NICKNAME, U.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;



