-- 코드를 입력하세요
-- 부모테이블: MEMBER_PROFILE, 자식테이블: REST_REVIEW
-- 조인키: MEMBER_ID
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD')
FROM REST_REVIEW R JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (
SELECT MEMBER_ID FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM REST_REVIEW
GROUP BY MEMBER_ID)
    )
ORDER BY REVIEW_DATE, REVIEW_TEXT